### PR TITLE
Move to docker GH actions

### PR DESCRIPTION
**Pull request by hardillb**
This lets us use docker buildx to build multiplatform containers and apply some better rules to the tagging

https://github.com/docker/login-action
https://github.com/docker/metadata-action
https://github.com/docker/setup-qemu-action
https://github.com/docker/setup-buildx-action
https://github.com/docker/build-push-action

### CODE REVIEW

**Comment by ZJvandeWeg** [comment]
Looks fine, but I don't like commented out code. Can it be removed?

**Comment by hardillb** [comment]
Yes it can, I left it in to help explain what the new stuff was doing, I will remove it

**Comment by hardillb** [comment]
Commented out code removed, added some basic explanation comments to new steps

**Comment by hardillb** [comment]
fixes #42

**Pull request merged**
